#!/bin/bash

# config file for borders, which adds border highlights to focused window
# install it with:
#
# brew tap FelixKratz/formulae
# brew install borders
#
# then enable:
#
# brew services start borders
#
# place this file under .config/borders/bordersrc

#!/bin/bash

options=(
	style=round
	width=4.0
	hidpi=off
	active_color="gradient(top_left=0xee33ccff,bottom_right=0xee00ff99)"
	inactive_color=0xaa595959
)

borders "${options[@]}"
# active_color=0xffd33682
# inactive_color=0xff839496
